const headerTitleBlack = 'header__title_black';
const headerTitleWhite = 'header__title_white';
const hamburger = 'header__icon_hamburger';
const headerBgWhite= "header__container_white";
const headerBgTransparent =  "header__container_transparent";
const headerBgBlack =  "header__container_black";
const hiddenNavDrawer = 'navigator_hidden';
const showNavDrawer = '';
const hamburgerBlack = 'header__icon_hamburger-black';
const hamburgerWhite = 'header__icon_hamburger-white';
const iconX = 'header__icon_x';
const noButton = 'header__button_hidden';
export {headerBgBlack, headerBgTransparent, noButton, iconX, headerBgWhite, headerTitleBlack, headerTitleWhite, hamburger, hamburgerBlack, hamburgerWhite, hiddenNavDrawer, showNavDrawer };